version: '3'
services:

  master:
    build: master
    #command: "server --tls-san 192.168.1.38 --kube-apiserver-arg advertise-address=192.168.1.38 --kube-apiserver-arg external-hostname=192.168.1.38"
    command: k3s server
    tmpfs:
      - /run
      - /var/run
      - /tmp
      - /var/log
    privileged: true
    read_only: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ./.data/master/etc_rancher:/etc/rancher
      - ./.data/master/var_lib:/var/lib
      - ./.data/master/output:/output
    ports:
      - 6443:6443
