version: '3'
services:

  server:
    build: ./server
    #command: "server --tls-san 192.168.1.38 --kube-apiserver-arg advertise-address=192.168.1.38 --kube-apiserver-arg external-hostname=192.168.1.38"
    command: k3s server
    tmpfs:
      - /run
      - /var/run
      - /tmp
      - /var/log
    privileged: true
    read_only: true
    environment:
      - K3S_TOKEN=36708781928298363503956007486665
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
      - K3S_NODE_EXTERNAL_IP=192.168.1.38
    volumes:
      - ./.data/server/etc_rancher:/etc/rancher
      - ./.data/server/var_lib:/var/lib
      - ./.data/server/output:/output
    ports:
      - 6443:6443
