version: '3'
services:

  worker:
    build: worker
    command: k3s agent
    tmpfs:
      - /run
      - /var/run
      - /tmp
      - /var/log
    privileged: true
    read_only: true
    volumes:
      - ./.data/worker/etc_rancher:/etc/rancher
      - ./.data/worker/var_lib:/var/lib

